### ISSUE TITLE
Artifactory resolution support

### ISSUE THREAD

**Issue by patrick-wright** [chef/qa-chef-server-cluster#6]
Now that artifactory keywork works to reference current release it also needs to support:
- "latest" stable
- latest "current"
- specific versions: "12.0.1+20150113170219.git.19.6f10ce8"

**Comment by patrick-wright** [comment]
@schisamo Please review my proposed artifactory resolution params. I'd like to get this nailed down before I start coding.
```
chef-server as example

= latest stable defaults =
artifactory         # => 12.0.1
latest-stable       # => 12.0.1

= current latest based on latest stable =
artifactory:current-latest # => 12.0.1+20150114180018.git.21.ed2021c
current-latest             # => 12.0.1+20150114180018.git.21.ed2021c

=  current latest based on specified version =
artifactory:current-latest:12.0.0 # => 12.0.0+20141217191420.git.54.404c006

= specfied version =
artifactory:12.0.0
artifactory:12.0.1+20150114180018.git.21.ed2021c
```

**Comment by patrick-wright** [comment]
I removed the `artifactory` keyword.  I really don't think its necessary.  I'll add functionality to match on `http` and make that the special case.

**Comment by schisamo** [comment]
For consistency should we make sure "latest" is the prefix? So `latest-stable` and `latest-current`. This would map the to the external __current__ and __stable__ channels (e.g. PackageCloud and Omnitruck) and associated __omnibus-current-local__ and __omnibus-stable-local__ repos in Artifactory.

**Comment by patrick-wright** [comment]
+1.  Can you think of any scenarios of artifact resolution I am missing?

**Comment by schisamo** [comment]
This looks good!

**Comment by patrick-wright** [comment]
WIP PR: https://github.com/opscode-cookbooks/artifactory/pull/27/
