### ISSUE TITLE
README Chef Zero instructions needs a `berks vendor` right?

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/qa-chef-server-cluster#84]
I had to run the following command to put the cookbooks in the correct location.

```
bundle exec berks vendor berks-cookbooks
```

https://github.com/chef/qa-chef-server-cluster#chef-zero

**Comment by patrick-wright** [comment]
Yes, master has gone though some major changes.  I haven't updated any docs yet, nor have I been disciplined about versioning.  I have a chore ticket to get everything up to speed and I integrate into Delivery.  Thanks for reporting this.

**Comment by jeremiahsnapp** [comment]
this has already been fixed here 927ad0db3acce6b82051adedd2c1d775e0f2a0d7
